# MUSE settings file

# Global settings
time_framework = [2020, 2022, 2024, 2026, 2028, 2030, 2032, 2034, 2036, 2038, 2040]
regions = ["R1"]
currency = 'MUS$2010'
interpolation_mode = 'linear'
log_level = 'info'
equilibrium_variable = 'demand'
maximum_iterations = 100
tolerance = 0.1
tolerance_unmet_demand = -0.1
excluded_commodities = ["wind"]

# Timeslices
[timeslices]
level_names = ["month", "day", "hour"]

[timeslices.all-year.all-week]
night = 1095
morning = 1095
mid-afternoon = 1095
early-peak = 1095
late-peak = 1095
evening = 1095
early-morning = 1095
late-afternoon = 1095

[global_input_files]
projections = '{path}/Projections.csv'
global_commodities = '{path}/GlobalCommodities.csv'

# Sectors
[sectors.residential]
type = 'default'
priority = 1
technodata = '{path}/residential/Technodata.csv'
commodities_in = '{path}/residential/CommIn.csv'
commodities_out = '{path}/residential/CommOut.csv'

[sectors.residential.subsectors.all]
agents = '{path}/Agents.csv'
existing_capacity = '{path}/residential/ExistingCapacity.csv'

[sectors.power]
type = 'default'
priority = 2
technodata = '{path}/power/Technodata.csv'
commodities_in = '{path}/power/CommIn.csv'
commodities_out = '{path}/power/CommOut.csv'

[sectors.power.subsectors.all]
agents = '{path}/Agents.csv'
existing_capacity = '{path}/power/ExistingCapacity.csv'

[sectors.gas]
type = 'default'
priority = 3
technodata = '{path}/gas/Technodata.csv'
commodities_in = '{path}/gas/CommIn.csv'
commodities_out = '{path}/gas/CommOut.csv'

[sectors.gas.subsectors.all]
agents = '{path}/Agents.csv'
existing_capacity = '{path}/gas/ExistingCapacity.csv'

[sectors.residential_presets]
type = 'presets'
priority = 0
consumption_path = "{path}/residential_presets/*Consumption.csv"

# Global outputs
[[outputs]]
quantity = "capacity"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"

[[outputs]]
quantity = "prices"
sink = "aggregate"
filename = "{cwd}/{default_output_dir}/MCA{Quantity}.csv"
